// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupRolloutPrefs.network.cookie.cookieBehavior", 4);
user_pref("app.normandy.user_id", "373ca6ca-15e5-4876-999d-7d817c1929ad");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1565531904);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1565533360);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1565613711);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1565531663);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1565610202);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1565531784);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1565533600);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1565533480);
user_pref("browser.cache.disk.amount_written", 6821);
user_pref("browser.cache.disk.capacity", 286720);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contentblocking.introCount", 5);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1565429289);
user_pref("browser.laterrun.bookkeeping.sessionCount", 5);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 81);
user_pref("browser.newtabpage.activity-stream.impressionId", "{f12d40aa-a4a2-4dc9-ad31-e115d1d9a9f9}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1565615690450");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1565617470450");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1565613820130");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1565617420130");
user_pref("browser.search.region", "IN");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1565613735");
user_pref("browser.slowStartup.averageTime", 114378);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20190718161435");
user_pref("browser.startup.homepage_override.mstone", "68.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1565613694);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1565531644550");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("devtools.toolsidebar-height.inspector", 350);
user_pref("devtools.toolsidebar-width.inspector", 700);
user_pref("devtools.toolsidebar-width.inspector.splitsidebar", 350);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "68.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "1a7632912a4c42bcb6f0469134317fc1");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Fri, 09 Aug 2019 09:59:13 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1565531905);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20190718161435");
user_pref("extensions.lastAppVersion", "68.0.1");
user_pref("extensions.lastPlatformVersion", "68.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{4d211360-ac03-46f1-9712-d81f7c6fea07}\",\"addons\":{\"webcompat@mozilla.org\":{\"version\":\"5.0.2\"}}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"aa5bd87a-5ae7-41ea-985a-d6ababc4494a\",\"fxmonitor@mozilla.org\":\"d101f6d8-cd91-45dd-b1e3-0baa27b886a0\",\"screenshots@mozilla.org\":\"cb207a4b-bb93-4219-94d2-1750e07d383e\",\"webcompat-reporter@mozilla.org\":\"5a33491e-9456-4de8-bc08-2b0cb42c4094\",\"webcompat@mozilla.org\":\"3a334acf-5428-44cc-9384-3c050ba5bd29\",\"default-theme@mozilla.org\":\"5ca3350e-7743-40c4-96cc-b506dd172930\",\"google@search.mozilla.org\":\"dbba3866-915c-4c46-9a7e-5f53429eb4c2\",\"amazondotcom@search.mozilla.org\":\"c5aca320-3fc2-40ef-9188-bdb256ec59a9\",\"bing@search.mozilla.org\":\"6f9c28ea-98ca-4d90-919d-0abef5c5e319\",\"ddg@search.mozilla.org\":\"4e07a689-df46-42fc-b16b-ac754a1e1b5f\",\"ebay@search.mozilla.org\":\"f08d1c3f-585f-472d-a2d5-81e618cf2ee2\",\"twitter@search.mozilla.org\":\"91ec4958-018f-425d-9b37-6212712dcbfb\",\"wikipedia@search.mozilla.org\":\"b18420c7-d486-42b8-96ed-8b70359a99c7\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("idle.lastDailyNotification", 1565535899);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1565531909);
user_pref("media.gmp-gmpopenh264.version", "1.8.1");
user_pref("media.gmp-manager.buildID", "20190718161435");
user_pref("media.gmp-manager.lastCheck", 1565533484);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", false);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1565535901);
user_pref("places.history.expiration.transient_current_max_pages", 58905);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "80bbe5c6-eaeb-4134-aa35-8eef344f6c4e");
user_pref("security.sandbox.plugin.tempDirSuffix", "7c636358-73e5-48b9-ab07-5c192a40cf54");
user_pref("services.blocklist.pinning.checked", 1565533764);
user_pref("services.settings.clock_skew_seconds", -280);
user_pref("services.settings.last_etag", "\"1565481679319\"");
user_pref("services.settings.last_update_seconds", 1565533764);
user_pref("services.settings.main.cfr-fxa.last_check", 1565533764);
user_pref("services.settings.main.cfr.last_check", 1565533764);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1565533764);
user_pref("services.settings.main.hijack-blocklists.last_check", 1565533764);
user_pref("services.settings.main.language-dictionaries.last_check", 1565533764);
user_pref("services.settings.main.normandy-recipes.last_check", 1565533764);
user_pref("services.settings.main.onboarding.last_check", 1565533764);
user_pref("services.settings.main.sites-classification.last_check", 1565533764);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1565533764);
user_pref("services.settings.security.onecrl.checked", 1565533764);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1565535900);
user_pref("toolkit.startup.last_success", 1565613661);
user_pref("toolkit.telemetry.cachedClientID", "3277b843-4c1c-4233-8afa-c7c243d4a97d");
user_pref("toolkit.telemetry.previousBuildID", "20190718161435");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
